In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly
import plotly.express as px

import plotly.graph_objects as go

In [ ]:
df = pd.read_csv("/content/supermarket_sales.csv")
df

In [ ]:
df.isnull().sum()  # returns number of null values in the dataset

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])    # converts date column from string to real time date format

In [ ]:
df["year"] = df["Date"].dt.year
df["month"] = df["Date"].dt.month #creating time features
df["Date"] = df["Date"].dt.day

In [ ]:
#recheck if there are any null values after feature extraction
df.isnull().sum()
df.duplicated().sum()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df["Hour"] = pd.to_datetime(df["Time"]).dt.hour

def slot(h):
    if h < 12: return "Morning"
    elif h < 17: return "Afternoon"
    else: return "Evening"

df["Time_slot"] = df["Hour"].apply(slot)

/tmp/ipython-input-3152/1896793330.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Hour"] = pd.to_datetime(df["Time"]).dt.hour

In [ ]:
sales_branch = df.groupby("Branch")["Total"].sum()
sales_branch

Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64

In [ ]:
df["Product line"] = df["Product line"].str.split(" and ")
df = df.explode("Product line")

In [ ]:
sales_product = df.groupby("Product line")["Total"].sum().sort_values()
sales_product

Product line
Health                    49193.7390
beauty                    49193.7390
Home                      53861.9130
lifestyle                 53861.9130
Fashion accessories       54305.8950
Electronic accessories    54337.5315
travel                    55122.8265
Sports                    55122.8265
beverages                 56144.8440
Food                      56144.8440
Name: Total, dtype: float64

In [ ]:
sales_month = df.groupby(["month" , "Product line"])["Total"].sum()
sales_month

month  Product line
1      Electronic accessories    18831.2880
       Fashion accessories       19345.1160
       Food                      19570.5300
       Health                    16383.1710
       Home                      20494.7400
       Sports                    21667.0230
       beauty                    16383.1710
       beverages                 19570.5300
       lifestyle                 20494.7400
       travel                    21667.0230
2      Electronic accessories    17362.9050
       Fashion accessories       19009.8615
       Food                      20000.3580
       Health                    14602.2555
       Home                      12434.3835
       Sports                    13809.6105
       beauty                    14602.2555
       beverages                 20000.3580
       lifestyle                 12434.3835
       travel                    13809.6105
3      Electronic accessories    18143.3385
       Fashion accessories       15950.9175
       Food                      16573.9560
       Health                    18208.3125
       Home                      20932.7895
       Sports                    19646.1930
       beauty                    18208.3125
       beverages                 16573.9560
       lifestyle                 20932.7895
       travel                    19646.1930
Name: Total, dtype: float64

In [ ]:
sales_gender = df.groupby(["Gender", "Product line"])["Total"].sum()
sales_gender

Gender  Product line
Female  Electronic accessories    27102.0225
        Fashion accessories       30437.4000
        Food                      33170.9175
        Health                    18560.9865
        Home                      30036.8775
        Sports                    28574.7210
        beauty                    18560.9865
        beverages                 33170.9175
        lifestyle                 30036.8775
        travel                    28574.7210
Male    Electronic accessories    27235.5090
        Fashion accessories       23868.4950
        Food                      22973.9265
        Health                    30632.7525
        Home                      23825.0355
        Sports                    26548.1055
        beauty                    30632.7525
        beverages                 22973.9265
        lifestyle                 23825.0355
        travel                    26548.1055
Name: Total, dtype: float64

In [ ]:
payment_counts = df["Payment"].value_counts()
payment_counts

Payment
Ewallet        572
Cash           560
Credit card    520
Name: count, dtype: int64

In [ ]:
rating_product = df.groupby("Product line")["Rating"].mean().sort_values()
rating_product

Product line
Home                      6.837500
lifestyle                 6.837500
travel                    6.916265
Sports                    6.916265
Electronic accessories    6.924706
Health                    7.003289
beauty                    7.003289
Fashion accessories       7.029213
beverages                 7.113218
Food                      7.113218
Name: Rating, dtype: float64

In [ ]:
sales_month_category = df.groupby(
    ["month", "Product line"]
)["Total"].sum().reset_index()

fig1 = px.bar(
    sales_month_category,
    x="month",
    y="Total",
    color="Product line",
    barmode="group",
    title="Sales per Month by Category",
    text_auto=True,
    template="plotly_dark"
)

fig1.show()

In [ ]:
cat_rev = df.groupby("Product line")["Total"].sum().reset_index()

fig2 = px.bar(
    cat_rev,
    x="Product line",
    y="Total",
    color="Total",
    title="Revenue by Product Category",
    text_auto=True,
    template="plotly_dark"
)

fig2.show()

In [ ]:
branch_rev = df.groupby("Branch")["Total"].sum().reset_index()

fig3 = px.bar(
    branch_rev,
    x="Branch",
    y="Total",
    color="Branch",
    text_auto=True,
    title="Revenue by Branch",
    template="plotly_dark"
)

fig3.show()

In [ ]:
fig4 = px.pie(
    df,
    names="Payment",
    title="Payment Method Share",
    template="plotly_dark"
)

fig4.show()

In [ ]:
month_rev = df.groupby("month")["Total"].sum().reset_index()

fig5 = px.line(
    month_rev,
    x="month",
    y="Total",
    markers=True,
    title="Monthly Revenue Trend",
    template="plotly_dark"
)

fig5.show()

In [ ]:
fig6 = px.histogram(
    df,
    x="Rating",
    nbins=20,
    title="Customer Rating Distribution",
    template="plotly_dark",
    text_auto=True
)

fig6.show()

In [ ]:
slot_rev = df.groupby("Time_slot")["Total"].sum().reset_index()

fig7 = px.bar(
    slot_rev,
    x="Time_slot",
    y="Total",
    color="Time_slot",
    text_auto=True,
    title="Revenue by Time Slot",
    template="plotly_dark"
)
fig7.show()

In [ ]:
pip install dash

Collecting dash
  Downloading dash-4.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.3)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.6)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from dash) (5.24.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from dash) (8.7.1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash) (4.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from dash) (2.32.4)
Collecting retrying (from dash)
  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from dash) (75.2.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (3.0.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.0.0->dash) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=5.0.0->dash) (26.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (2026.1.4)
Downloading dash-4.0.0-py3-none-any.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 24.1 MB/s eta 0:00:00
Downloading retrying-1.4.2-py3-none-any.whl (10 kB)
Installing collected packages: retrying, dash
Successfully installed dash-4.0.0 retrying-1.4.2

In [ ]:
!pip install jupyter-dash dash plotly

Collecting jupyter-dash
  Downloading jupyter_dash-0.4.2-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: dash in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from jupyter-dash) (2.32.4)
Requirement already satisfied: flask in /usr/local/lib/python3.12/dist-packages (from jupyter-dash) (3.1.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from jupyter-dash) (1.4.2)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from jupyter-dash) (7.34.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from jupyter-dash) (6.17.1)
Collecting ansi2html (from jupyter-dash)
  Downloading ansi2html-1.9.2-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from jupyter-dash) (1.6.0)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.6)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from dash) (8.7.1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from dash) (75.2.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from flask->jupyter-dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from flask->jupyter-dash) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from flask->jupyter-dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from flask->jupyter-dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from flask->jupyter-dash) (3.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter-dash) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter-dash) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter-dash) (0.2.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter-dash) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter-dash) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter-dash) (6.5.1)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter-dash) (5.7.1)
Collecting jedi>=0.16 (from ipython->jupyter-dash)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->jupyter-dash) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->jupyter-dash) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->jupyter-dash) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->jupyter-dash) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->jupyter-dash) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->jupyter-dash) (4.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->jupyter-dash) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->jupyter-dash) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->jupyter-dash) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->jupyter-dash) (2026.1.4)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->jupyter-dash) (0.8.6)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel->jupyter-dash) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel->jupyter-dash) (5.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel->jupyter-dash) (2.9.0.post0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->jupyter-dash) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyter-dash) (0.6.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel->jupyter-dash) (4.9.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel->jupyter-dash) (1.17.0)
Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Downloading ansi2html-1.9.2-py3-none-any.whl (17 kB)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 11.5 MB/s eta 0:00:00
Installing collected packages: jedi, ansi2html, jupyter-dash
Successfully installed ansi2html-1.9.2 jedi-0.19.2 jupyter-dash-0.4.2

In [ ]:
!pip install dash --upgrade

Requirement already satisfied: dash in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.3)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash) (3.1.6)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from dash) (5.24.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from dash) (8.7.1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash) (4.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from dash) (2.32.4)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from dash) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from dash) (75.2.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash) (3.0.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.0.0->dash) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=5.0.0->dash) (26.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->dash) (2026.1.4)

In [ ]:
from dash import Dash, html, dcc

app = Dash(__name__)

app.layout = html.Div([
    html.H1("Supermarket Sales Analytics Dashboard"),
    dcc.Graph(figure=fig1),
    dcc.Graph(figure=fig2),
    dcc.Graph(figure=fig3),
    dcc.Graph(figure=fig4),
    dcc.Graph(figure=fig5),
    dcc.Graph(figure=fig6),
    dcc.Graph(figure=fig7),
])

app.run(jupyter_mode="external")

Dash is running on http://127.0.0.1:8050/

INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__'
 * Debug mode: off